channels:
  - krodriguez
  - usgs-astrogeology
  - conda-forge
  - probcomp
  - anaconda
  - defaults
dependencies:
   - mock
   - pytest
   - click
   - requests
   - geopandas
   - pvl
   - pywget
   - geoalchemy2
   - jupyter
   - plio
   - psycopg2
